### ISSUE TITLE
Next (snapshot) release on maven, including RDF4J integration

### ISSUE THREAD

**Issue by QuarksToQuasars** [semarglproject/semargl#46] opened 2016-11-21 10:47 UTC
Can you provide some context about what is missing for a new release / publishing a new maven artifact? Getting the travis build passing again ?

#44

**Comment by ansell** [comment] 2016-11-21 22:13
The release is blocked on both getting the build working with the new tests which are automatically pulled in by the test suite, and giving me permissions at Sonatype to do the release.

**Comment by lewismc** [comment] 2016-11-25 22:22
... this is a shame.

**Comment by levkhomich** [comment] 2016-11-26 14:45
@ansell 
What tests are you referring to? Because failing ones (RDFa) are in the repo.

Anyway, they were fixed by levkhomich@fcbad32c61812c9716fdd4f153799f1afb43153e). Not sure why [original test suite repo](https://github.com/rdfa/rdfa-website/tree/master/tests) still contains broken tests (240-245).

I'm not aware about any Sonatype collaboration tools. I can definitely give you any permissions needed, but I will need some guidance on that :) If there is any rush, I can release what we have right now.

@lewismc this is not helpful.

**Comment by lewismc** [comment] 2016-11-26 16:01
@levkhomich I meant nothing bad by it. I genuinely meant that it is a shame.
Let me lend a hand. If you need some guidance and you wish to release the library in its current form then you can add @ansell to the groupId over on [OSSRH-9123](https://issues.sonatype.org/browse/OSSRH-9123) or [OSSRH-9106](https://issues.sonatype.org/browse/OSSRH-9106) and by tagging **jorlina**. 
Again I want to say that I was not trying to be unhelpful.

**Comment by ansell** [comment] 2016-11-27 22:14
Hi Lev, thanks for fixing the broken RDFa tests. I will look into why some RDFa tests are now failing for the new RDF4J integration module, which may be related to it using RDF-1.1 rather than RDF-1.0.

The Jira that I was referring to is the issue tracker that Sonatype use to give people permissions to deploy to Maven Central, known as "OSSRH". The relevant issue which you need to reopen and comment on to get Sonatype to give me permissions to deploy artifacts into the "org.semarglproject" groupId is either https://issues.sonatype.org/browse/OSSRH-9123 or https://issues.sonatype.org/browse/OSSRH-9106 as Lewis linked to above. My username at OSSRH is "p_ansell"

**Comment by levkhomich** [comment] 2016-11-28 00:55
The problem is that both of these tickets are linked to my personal groupId. That is not the best option, if Sonatype allows to manage access only at the level of group. And, if it is the case, we should probably consider Bintray, as it enables fine-grained control over artifacts.

**Comment by ansell** [comment] 2016-11-28 01:19
Sorry, I thought that OSSRH-9123 was outside of your personal groupId, although the closure of it as a duplicate was a little confusing. 

I don't mind if we change the groupId to something that isn't linked to that org.semarglproject and is neutral from your personal space. That would just require opening a new OSSRH ticket which would be fairly quickly resolved given past timelines.

I don't like the way Bintray operates, and have had bad experiences with it in the past having had artifacts that aren't official releases uploaded to it and released as if they were official releases (without changing the groupId). OSSRH doesn't seem to have those issues, as at least someone needs to change the groupId to upload their own releases.

**Comment by levkhomich** [comment] 2016-11-28 21:12
Ok, so we need new groupId. What do you think about creating GitHub organization and using com.github.semargl for publishing?

**Comment by ansell** [comment] 2016-11-28 21:55
That works for me. https://github.com/semargl is taken by a user right now, but we could go for https://github.com/semarglproject

**Comment by ansell** [comment] 2016-11-29 22:15
Hi Lev, I created the semarglproject organisation and invited you to it. Would you be okay with moving this repository into that organisation to keep forks/stars/watchers intact?

**Comment by levkhomich** [comment] 2016-12-04 14:31
@ansell done

**Comment by ansell** [comment] 2016-12-07 00:28
I have uploaded a 0.7-SNAPSHOT to the sonatype snapshots repository. Will wait a few days for interested parties to review it before releasing.

**Comment by QuarksToQuasars** [comment] 2016-12-08 22:23
I have added semarql together with semargl-rdf4j using the 0.7-SNAPSHOT and re-activated some old, tiny integration tests. Works like a charm. Thank you guys!

**Comment by ansell** [comment] 2016-12-09 00:46
0.7 has been released, will be available on Maven Central in a few hours when the sync happens.

**Closed by ansell** 2016-12-09 00:46 UTC
